version: '3.9'

services:
  # Grafana container
  grafana-chapter2:
    image: grafana/grafana:9.4.7-ubuntu
    container_name: grafana-chapter2
    #Expose localhost port and match with container port
    ports:
      - 3000:3000
    volumes:
      - "./data:/var/lib/grafana"
