server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
# Docker job, scrap docker container log to Loki
- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker-log
      __path__: /var/lib/docker/containers/*/*log
- job_name: myLog_001
  static_configs:
  - targets:
      - localhost
    labels:
      job: mylog_001
      __path__: /var/lib/mylog/myLog.log
- job_name: MyLog_002
  static_configs:
  - targets:
      - localhost
    labels:
      job: mylog_002
      __path__: /var/lib/mylog/myLog2.log