{
 "title": "7.03 Loki Log 2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "keyword", "label": "Loki Query Filter" }
  ]
 },
 "panels": [
  {
   "title": "Loki TS Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({job=\"mylog_001\"} |= \"$keyword\"[$__interval])"
    }
   ]
  },
  {
   "title": "Opera Log Panel with Variabel - MyLog_001",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/mylog/myLog.log\",job=\"mylog_001\"} |~ \"$keyword\""
    }
   ]
  },
  {
   "title": "Logs Panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"mylog_002\"}"
    }
   ]
  }
 ]
}