version: '3.9'

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - prometheus

  telegraf:
    image: telegraf:1.19
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - prometheus

volumes:
  # Create docker volume to store Prometheus data
  influxdb-storage:

# Create docker network, name prometheus with bridge type
networks:
  prometheus:
    driver: bridge
